version: "3.2"
services:
  app:
    container_name: poronga
    image: moviedomfo/express_auth
    ports:
      - "3003:3003"
      - "3001:3001"
    environment:
      - PORT=${PORT}
      - SERVER_NAME="DEFAULT AUTH0 ${NODE_ENV}"
#  platon:
#     image: moviedomfo/express_auth  
#     container_name: platon
#     ports:
#       - "3011:3011"
#       - "3002:3001"
#     environment:
#       - PORT=3011
#  nginx:
#     image: nginx:latest
#     restart: always
#     build:
#         context: ./nginx
#     ports:
#        - 6000:80
#        - 443:443